## Intro to Numpy

Textbook: https://datawranglingpy.gagolewski.com/index.html

ndarray: N-dimensional array 

(2, 1, 0)

N=0 -> numero, "scalare" esempio: 5
N=1 -> vettore, esempio (2, 1, 0)
N=2 -> matrici

2 3 4
1 1 1
2 3 1

N>2 -> tensori

In [1]:
import numpy as np

In [2]:
n = 10000

In [3]:
%timeit [ e**2 for e in range(n) ]

2.05 ms ± 19.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit np.arange(n)**2

6.76 µs ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
# write a function to compute the variance of x
def variance(x):
    n = len(x)
    
    m = 0.0
    for i in range(n):
        m += x[i]
    m /= n
    
    s = 0.0
    for i in range(n):
        s += (x[i]-m)**2
    s /= n-1
    
    return s

In [6]:
x = np.random.random(10_000)

In [7]:
%timeit variance(x)
%timeit np.var(x, ddof=1)
%timeit x.var(ddof=1)
%timeit np.sum((x-np.mean(x))**2)/(len(x)-1)

3.01 ms ± 9.94 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
15.4 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
14.7 µs ± 88.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
13.6 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Creazione di arrays

ndarray: N-dimensional array 

(2, 1, 0)

N=0 -> numero, "scalare" esempio: 5
N=1 -> vettore, esempio (2, 1, 0)
N=2 -> matrici

2 3 4
1 1 1
2 3 1

N>2 -> tensori

In [8]:
x = np.arange(10)

In [9]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
type(x)

numpy.ndarray

In [11]:
x.ndim

1

In [14]:
x.shape[0]

10

In [15]:
x.dtype

dtype('int64')

In [21]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
A = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

In [30]:
A.ndim

2

In [31]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
A.shape

(3, 3)

In [36]:
m = np.array(1)

In [39]:
m.ndim

0

In [40]:
A * A

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [41]:
A @ A.T

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

#### Reshaping

In [51]:
B = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]
])

In [52]:
B.shape = (12, 1)

In [53]:
B

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [56]:
B.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [57]:
B.reshape(6, -1) * B.reshape(3, -1)

ValueError: operands could not be broadcast together with shapes (6,2) (3,4) 

### Aggregate Functions

In [59]:
B.shape = (4, 3)

In [60]:
B

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
B.sum()

78

In [62]:
np.sum(B, axis=1)

array([ 6, 15, 24, 33])

In [63]:
np.sum(B, axis=0)

array([22, 26, 30])

## Esercizi

1. Write a function which standardizes the values in a given
numeric vector, i.e., rescales its elements so that the resulting vector
is of mean and standard deviation of 1.
Note: this is also called "Z-score computing". (da testare su un singolo vettore, ndim=1)

2. Write a function which standardizes the values in each column of
a given matrix (separately). (da testare su oggetto ndim=2)