## Intro to Numpy

Textbook: https://datawranglingpy.gagolewski.com/index.html

ndarray - N-dimensional array

N=0 -> "scalare", numero
N=1 -> vettore
N=2 -> matrice
N>2 -> tensore 

In [1]:
import numpy as np

In [2]:
a = np.array(5)

In [3]:
a

array(5)

In [4]:
a*2

10

In [7]:
a.ndim

0

In [5]:
b = np.array([1, 2, 3, 4])

In [6]:
b

array([1, 2, 3, 4])

In [8]:
b.ndim

1

In [9]:
b.shape

(4,)

In [10]:
M = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [11]:
M.ndim

2

In [12]:
M.shape

(3, 4)

In [13]:
M2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

In [18]:
M2

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [15]:
M2.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [16]:
M * M

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [17]:
M2 * M2

TypeError: can't multiply sequence by non-int of type 'list'

In [19]:
# prodotto scalare
M @ M.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [20]:
type(M)

numpy.ndarray

In [21]:
type(a)

numpy.ndarray

In [23]:
n = 10000
%timeit [ e**2 for e in range(n) ]

2.05 ms ± 6.04 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%timeit np.arange(n)**2

8.72 µs ± 238 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [25]:
# write a function to compute the variance of x
def variance(x):
    n = len(x)
    
    m = 0.0
    for i in range(n):
        m += x[i]
    m /= n
    
    s = 0.0
    for i in range(n):
        s += (x[i]-m)**2
    s /= n-1
    
    return s

In [26]:
x = np.random.random(10_000)

In [27]:
%timeit variance(x)
%timeit np.var(x, ddof=1)
%timeit x.var(ddof=1)
%timeit np.sum((x-np.mean(x))**2)/(len(x)-1)

2.98 ms ± 6.28 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
15.3 µs ± 72.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
14.6 µs ± 53.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
16.3 µs ± 309 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Creazione di arrays

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
np.zeros(10, dtype=bool)

array([False, False, False, False, False, False, False, False, False,
       False])

In [33]:
M = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [34]:
M.shape

(3, 4)

In [35]:
M.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
M.reshape(9, 8)

ValueError: cannot reshape array of size 12 into shape (9,8)

In [37]:
M.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [38]:
M.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

### Aggregate function

In [39]:
M2

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [41]:
s = 0
for i in M2:
    for j in i:
        s += int(j)

s

78

In [42]:
s2 = []
for i in M2:
    h = 0
    for j in i:
        h += j
    s2.append(h)
    
s2

[10, 26, 42]

In [43]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
M.sum()

78

In [46]:
np.sum(M, axis=1)

array([10, 26, 42])

In [47]:
np.sum(M, axis=0)

array([15, 18, 21, 24])

## Esercizi

1. Write a function which standardizes the values in a given
numeric vector, i.e., rescales its elements so that the resulting vector
is of mean and standard deviation of 1.
Note: this is also called "Z-score computing". (lavorare su ndim=1)

2. Write a function which standardizes the values in each column of
a given matrix (separately). (lavorare su ndim=2)